version: "3.3"
services:
  cwmonitor:
    build: ..
    image: dedalusj/cwmonitor:latest
    command: >
      --hostid test
      --metrics cpu,memory,disk,swap,docker-stats,docker-health
      --metrics.dockerlabel "com.cwmonitor.name"
      --interval 20
      --namespace ${NAMESPACE}
      --debug
    container_name: cwmonitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  healthy:
    image: alpine:3.8
    command: /bin/sh -c "while true; do sleep 1; done"
    container_name: healthy
    healthcheck:
      test: exit 0
      interval: 5s
  unhealthy:
    image: alpine:3.8
    command: /bin/sh -c "while true; do sleep 1; done"
    labels:
      com.cwmonitor.name: "unhealthy"
    healthcheck:
      test: exit 1
      interval: 5s
